name: Deploy

on:
  push:
    branches: [prd, stg]
    paths-ignore: # Pushes that include only these changed files won't trigger actions
      - "**/README.md"
      - "**/.gitignore"
      - "**/doc/*"

env:
  tf_version: ">=1.4.5" # must match value in terraform-iac/*/app/main.tf

jobs:
  env:
    name: Set Env Vars
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Timestamp
        id: date
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Set up PRD Environment Variables
        if: github.ref == 'refs/heads/prd'
        # Replace the app_name with the project name
        run: |
          matrix='{
              "env":[
                  {
                      "app_name":"app-name",
                      "tf_working_dir":"./terraform/prd",
                      "aws_key_name":"byu_dept_fhtl_prd_key",
                      "aws_secret_name":"byu_dept_fhtl_prd_secret",
                      "image_tag":"${{ steps.date.outputs.timestamp }}"
                  }
              ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

      - name: Set up STG Environment Variables
        if: github.ref == 'refs/heads/stg'
        # Replace the app_name with the project name
        run: |
          matrix='{
              "env":[
                  {
                      "app_name":"app-name",
                      "tf_working_dir":"./terraform/stg",
                      "aws_key_name":"byu_dept_fhtl_dev_key",
                      "aws_secret_name":"byu_dept_fhtl_dev_secret",
                      "image_tag":"${{ steps.date.outputs.timestamp }}"
                  }
              ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

    outputs:
      matrix: ${{ env.matrix }}

  changes:
    name: Filter by File Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3

      - name: Filter the paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'docker/**'
            frontend:
              - 'frontend/**'

  format:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            terraform

      - name: Check Terraform Formatting
        working-directory: "./terraform"
        run: terraform fmt -check -recursive

  ecr-repo:
    name: Deploy the AWS ECR Repository
    runs-on: ubuntu-latest
    needs: [env, format]
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            terraform

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets[matrix.env.aws_key_name] }}
          aws-secret-access-key: ${{ secrets[matrix.env.aws_secret_name] }}
          aws-region: us-west-2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Terraform Init
        working-directory: "${{ matrix.env.tf_working_dir }}"
        run: terraform init

      - name: Terraform Plan
        working-directory: "${{ matrix.env.tf_working_dir }}"
        run: terraform plan -target="module.app.aws_ecr_repository.ecr_repo" -var 'image_tag=${{ matrix.env.image_tag }}' -input=false -out=plan

      - name: Terraform Apply
        working-directory: "${{ matrix.env.tf_working_dir }}"
        run: terraform apply plan

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [env, ecr-repo, changes]
    if: ${{ needs.changes.outputs.backend == 'true' }}
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            docker
            backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets[matrix.env.aws_key_name] }}
          aws-secret-access-key: ${{ secrets[matrix.env.aws_secret_name] }}
          aws-region: us-west-2

      - name: Log into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push the Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: "${{ matrix.env.app_name }}-repo"
          APP_NAME: ${{ matrix.env.app_name}}
          IMAGE_TAG: ${{ matrix.env.image_tag }}
        run: |
          docker build backend --file docker/Dockerfile --tag $ECR_REGISTRY/$ECR_REPO:$APP_NAME-$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO:$APP_NAME-$IMAGE_TAG

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [env, format, build, changes]
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            terraform
            frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets[matrix.env.aws_key_name] }}
          aws-secret-access-key: ${{ secrets[matrix.env.aws_secret_name] }}
          aws-region: us-west-2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: "${{ matrix.env.tf_working_dir }}"
        run: terraform init

      - name: Terraform Plan
        working-directory: "${{ matrix.env.tf_working_dir }}"
        run: terraform plan -var 'image_tag=${{ matrix.env.image_tag }}' -input=false -out=plan

      - name: Terraform Apply
        working-directory: "${{ matrix.env.tf_working_dir }}"
        run: terraform apply plan

      - name: Get Terraform Outputs
        id: terraform-outputs
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        working-directory: "${{ matrix.env.tf_working_dir }}"
        run: |
          echo "s3_bucket=$(terraform output -raw s3_bucket)" >> $GITHUB_OUTPUT
          echo "cf_distribution_id=$(terraform output -raw cf_distribution_id)" >> $GITHUB_OUTPUT

      - name: Build React
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        working-directory: "frontend"
        run: |
          npm ci
          npm run build --if-present

      - name: Copy React code to S3 Site Bucket
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        run: aws s3 sync frontend/dist s3://${{ steps.terraform-outputs.outputs.s3_bucket }}

      - name: Invalidate CloudFront Cache
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        run: aws cloudfront create-invalidation --path '/*' --distribution-id ${{ steps.terraform-outputs.outputs.cf_distribution_id }}
